name: On Change
on:
   push:
       branches: - main
jobs:
   deploy:
        runs-on: ubuntu-latest
   steps:
       - name: Check code
         uses: actions/checkout@v2
       - name:
         uses: actions/checkout@v2
         with: 
             python-version: 'latest'
        #- name: install
             
        - name: Exec
            run: python railway.py
